global:
  scrape_interval: 15s

scrape_configs:
- job_name: node # стандартные строки из faq для node_exporter
  static_configs:
  - targets: ['node_exporter:9100'] # localhost из faq не канает из-за сети докера
